name: clevertap_plugin
description: The CleverTap Flutter SDK for Mobile Customer Engagement,Analytics and Retention solutions.
version: 1.9.1
homepage: https://github.com/CleverTap/clevertap-flutter

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.clevertap.clevertap_plugin
        pluginClass: CleverTapPlugin
      ios:
        pluginClass: CleverTapPlugin
